### ISSUE TITLE
CPU overload indicator constantly flashing

### ISSUE THREAD

**Issue by clarkcx** [neilbaldwin/SPECDRUM#4]
If I add a single instance of the plugin to a midi track in a new (empty) project and hit play the CPU indicator immediately lights up. The actual CPU meter bounces between 9% and 12%. This is without adding any samples or changing any parameters. Adding samples and playing around with things sounds okay but if I start to add other tracks I get audio glitches. 

MacBookPro M1 Max / 32GB RAM / macOS 13.3.1 / Ableton Live Suite 11.2.11

**Comment by neilbaldwin** [comment]
I'm still not seeing this issue and I've not had other reports. There may have been some behind-the-scenes fixes done recently that likely could've been contributing to the CPU load (for no good reason).

Would be interesting if anyone else has noticed this?
