### ISSUE TITLE
Change events being triggered in Live without me doing anything

### ISSUE THREAD

**Issue by clarkcx** [neilbaldwin/SPECDRUM#5]
In one of my test projects change events are being fired by Specdrum as soon as I hit play. I'm not sure exactly what's being changed but it means that if I edit something on another midi track (e.g. just click and drag a note or whatever) and then hit cmd-z the change won't undo. The Edit menu constantly shows Undo Change in "SPECDRUM". This seems to happen 100% of the time in the project I'm testing but hasn't happened in a second test project.

**Comment by neilbaldwin** [comment]
While it's impossible to stop SPECDRUM from writing to Live's undo buffer, changes I've made reduce this to a minimum and this is much improved now.
